version: "3"

services:
  app-node:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: app:node
    container_name: app-node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh index.js
    tty: true
    networks:
      - node-app-network
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx:prod
    container_name: nginx-node
    # entrypoint: dockerize -wait tcp://app-node:3001 -timeout 20s docker-entrypoint.sh
    tty: true
    networks:
      - node-app-network
    ports:
      - "8080:80"
    depends_on:
      - app-node

  db:
    image: mysql:8
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
    networks:
      - node-app-network

networks:
  node-app-network:
    driver: bridge
