version: "3"

services:
  app:
    build:
      context: ../node
    container_name: app
    entrypoint: sh -c "node index.js"
    networks:
      - node-network
    volumes:
      - ../node:/app
      - /app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
    networks:
      - node-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  node-network:
    driver: bridge
